name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_9842a259-dc8e-4fcc-8707-4c18e5fbbc83 }}
